---
repo-name: peripherals-vmware-vshpere
categories:
  - cloud
display-name: VMware vSphere
manufacturer: VMware
product: vSphere
description: VMware vSphere is a cloud computing platform for virtualization.
